services:
  app:
    build: .
    container_name: kalasya_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - APP_PORT=${APP_PORT}
      - DSN=${DSN}
      - AUTH_KEY=${AUTH_KEY}
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - CSRF_KEY=${CSRF_KEY}
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: kalasya_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
